### ISSUE TITLE
Decide whether to support `pydantic.BaseModel`

### ISSUE THREAD

**Issue by rogiervandergeer** [rogiervandergeer/pydargs#18]

**Comment by antonsteenvoorden** [comment]
Some differences mentioned here do not make me very enthusiastic about supporting BaseModel https://github.com/pydantic/pydantic/issues/710

**Comment by antonsteenvoorden** [comment]
This page also has some insights https://docs.pydantic.dev/latest/concepts/dataclasses/

**Comment by rogiervandergeer** [comment]
I suggest we only do dataclasses (for now)
