### ISSUE TITLE
pydargs considers `init=False` fields mandatory

### ISSUE THREAD

**Issue by diederikperdok** [rogiervandergeer/pydargs#55]
Consider the following script:
```python
from dataclasses import dataclass, field

from pydargs import parse


@dataclass
class Name:
    first_name: str
    last_name: str
    full_name: str = field(init=False)

    def __post_init__(self):
        self.full_name = f"{self.first_name} {self.last_name}"

parse(Name)
```

When called as `python example.py --first-name John --last-name Doe`, it errors: `example.py: error: the following arguments are required: --full-name` even though I can instantiate `Name` without supplying a value for `full_name`.

It's easily resolved in practice by giving `full_name` any default (e.g. an empty string) which is then immediately overwritten in `__post_init__`, so it's not a big issue. Still, it would be less surprising if pydargs and the dataclass itself agreed on which fields are  mandatory.

**Comment by antonsteenvoorden** [comment]
Another alternative is to [mark it as ignored to pydargs](https://github.com/rogiervandergeer/pydargs/blob/main/README.md#ignoring-fields):
```python
@dataclass
class Name:
    first_name: str
    last_name: str
    full_name: str = field(init=False, metadata=dict(ignore_arg=True))

    def __post_init__(self):
        self.full_name = f"{self.first_name} {self.last_name}"
```

But adding support for `init=False` makes sense 👍
